### ISSUE TITLE
android offerwall

### ISSUE THREAD

**Issue by prajitkk** [adgatemedia/adgate-rewards-android-sdk#1]
i followed the procedure given in the site, but how can i get the points rewarded for the user . Here only the number of conversions are given. can you please give us the code for getting points

**Comment by eblanshey** [comment]
Documentation has been updated, and the example code was added in the `seeLatestConversions` method of the MainActivity.

https://github.com/adgatemedia/adgate-rewards-android-sdk/blob/master/app/src/main/java/com/adgatereward/adgaterewardexample/MainActivity.java
