### ISSUE TITLE
Not able to use local aar files

### ISSUE THREAD

**Issue by jacaTM** [adgatemedia/adgate-rewards-android-sdk#2]
When trying to build I get the following error:

Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error).

Could the .aar be published to a maven repository (jitpack is not able to build this git repository as well)

**Comment by eblanshey** [comment]
Hi @jacaTM! I just pushed the library to a maven repository. Can you please try it and see if it works for you?

Make sure you have jitpack enabled in the root `build.gradle`:

```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

Add the dependency to your module:

```
	dependencies {
	        implementation 'com.gitlab.adgate-media:androidsdk:v2.0.1'
	}
```

If you can confirm it works we'll update our installation docs. Thanks!

**Comment by jpreiditsch** [comment]
@eblanshey the gitlab repository seems to have become private, we have been unable to pull in the agate dependency since tuesday.

**Comment by eblanshey** [comment]
Jitpack works, and the gitlab repository issue is fixed. Closing.
